apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 3
    image: quay.io/artemiscloud/activemq-artemis-operator:latest
    persistenceEnabled: true
    messageMigration: true
  acceptors:
  - name: amqp
    protocols: amqp
    port: 5672
    sslEnabled: true
